---
framework: jest
preRun:
     command:
        - npm ci
preMerge:
  pattern:
    - "./test/unit/**/*.spec.js"
#     - "./test/unit/*.spec.js"
#     - "./test/integration/*.spec.js"
postMerge:
  pattern: 
    - "./test/unit/**/*.spec.js"
#     - "./test/unit/*.spec.js"
#     - "./test/integration/*.spec.js"
postRun:
     command:
        - node --version
version: 1.0
